In [1]:
I = only.(mapreduce(permutedims, vcat, split.(readlines(open("input")), "")))

140×140 Matrix{Char}:
 'R'  'R'  'R'  'R'  'R'  'R'  'R'  'R'  …  'J'  'J'  'J'  'J'  'J'  'J'  'C'
 'R'  'R'  'R'  'R'  'R'  'R'  'R'  'R'     'J'  'J'  'J'  'J'  'J'  'J'  'C'
 'R'  'R'  'R'  'R'  'R'  'R'  'R'  'R'     'J'  'J'  'J'  'J'  'J'  'J'  'C'
 'R'  'R'  'R'  'R'  'R'  'R'  'R'  'R'     'J'  'J'  'J'  'J'  'J'  'J'  'C'
 'R'  'R'  'R'  'R'  'R'  'R'  'R'  'R'     'J'  'J'  'J'  'J'  'A'  'A'  'A'
 'R'  'R'  'R'  'R'  'R'  'R'  'R'  'R'  …  'J'  'J'  'A'  'A'  'A'  'A'  'A'
 'R'  'R'  'R'  'R'  'R'  'R'  'S'  'R'     'J'  'A'  'A'  'A'  'A'  'A'  'A'
 'R'  'S'  'R'  'R'  'R'  'R'  'S'  'S'     'A'  'A'  'A'  'A'  'A'  'A'  'A'
 'S'  'S'  'S'  'S'  'S'  'S'  'S'  'R'     'A'  'A'  'A'  'A'  'A'  'A'  'A'
 'S'  'S'  'S'  'S'  'S'  'S'  'S'  'S'     'A'  'A'  'A'  'A'  'A'  'A'  'A'
 ⋮                        ⋮              ⋱            ⋮                   
 'Q'  'Q'  'Q'  'B'  'B'  'U'  'B'  'B'     'S'  'S'  'S'  'S'  'S'  'S'  'S'
 'Q'  'Q'  'Q'  'B'  'B'  'B'  'B'  'B'     '

In [2]:
M = zeros(Int, size(I))

140×140 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 ⋮              ⋮              ⋮        ⋱        ⋮              ⋮           
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0    

In [3]:
inbounds(i) = 1 <= i[1] <= size(I,1) && 1 <= i[2] <= size(I,2)
up, right, down, left = CartesianIndex(-1, 0), CartesianIndex(0,1), CartesianIndex(1,0), CartesianIndex(0,-1)
unvisited_same_neighbor(i,v) = [i+d for d in [up, right, down, left] if inbounds(i+d) && I[i+d]==v && !((i+d) in visited)]

unvisited_same_neighbor (generic function with 1 method)

In [4]:
function floodfill(i, c)
    M[i] = c
    push!(visited, i)
    [floodfill(n, c) for n in unvisited_same_neighbor(i, I[i])]
end

floodfill (generic function with 1 method)

In [5]:
visited = []
c = 1
for i in CartesianIndices(I)
    (i in visited) && continue
    floodfill(i, c)
    c += 1
end

In [6]:
fence(i) = sum([!inbounds(i+d) || I[i+d] != I[i] for d in [up, right, down, left]])

fence (generic function with 1 method)

In [7]:
fences(v) = sum(fence(i) for i in findall(==(v), M))

fences (generic function with 1 method)

In [8]:
price(v) = fences(v) * count(==(v), M)

price (generic function with 1 method)

In [9]:
sum(price.(1:maximum(M)))

1375476

In [10]:
rotate_right = Dict(up=>right, right=>down, down=>left, left=>up)
rotate_left = Dict(up=>left, right=>up, down=>right, left=>down);

In [11]:
M

140×140 Matrix{Int64}:
  1   1   1   1   1   1   1   1   1   1  …  596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  602  602  602
  1   1   1   1   1   1   1   1   1   1  …  596  596  602  602  602  602  602
  1   1   1   1   1   1   2   1   1   1     596  602  602  602  602  602  602
  1   2   1   1   1   1   2   2   1   1     602  602  602  602  602  602  602
  2   2   2   2   2   2   2   1   1   1     602  602  602  602  602  602  602
  2   2   2   2   2   2   2   2   2   2     602  602  602  602  602  602  602
  ⋮                   ⋮                  ⋱              ⋮                 
 20  20  20  21  21  19  21  21  21  21     610  610  610  610  610  610  610
 20  20  20  21  21  21  21  21  21  21     

In [12]:
function h_edgefill!(drawn, i, v, D)
    drawn[i][D] = true
    d = left
    while (!inbounds(i+d+D) || M[i+d+D] != v) && inbounds(i+d) && M[i+d] == v 
        drawn[i+d][D] = true
        d += left
    end
    d = right
    while (!inbounds(i+d+D) || M[i+d+D] != v) && inbounds(i+d) && M[i+d] == v 
        drawn[i+d][D] = true
        d += right
    end
end

function v_edgefill!(drawn, i, v, D)
    drawn[i][D] = true
    d = up
    while (!inbounds(i+d+D) || M[i+d+D] != v) && inbounds(i+d) && M[i+d] == v 
        drawn[i+d][D] = true
        d += up
    end
    d = down
    while (!inbounds(i+d+D) || M[i+d+D] != v)  && inbounds(i+d) && M[i+d] == v 
        drawn[i+d][D] = true
        d += down
    end
end

v_edgefill! (generic function with 1 method)

In [13]:
function n_sides(v)
    all_idxs = findall(==(v), M)
    drawn = Dict(i=>Dict(up=>false, down=>false, left=> false, right=>false) for i in all_idxs)
    c = 0
    for i in all_idxs
        if (!inbounds(i+up) || M[i+up] != v) && !drawn[i][up]
            h_edgefill!(drawn, i, v, up)
            c += 1
        end
        if (!inbounds(i+down) || M[i+down] != v) && !drawn[i][down]
            println("d", i)
            h_edgefill!(drawn, i, v, down)
            c += 1
        end
        if (!inbounds(i+left) || M[i+left] != v) && !drawn[i][left]
            v_edgefill!(drawn, i, v, left)
            c += 1
        end
        if (!inbounds(i+right) || M[i+right] != v) && !drawn[i][right]
            v_edgefill!(drawn, i, v, right)
            c += 1
        end
    end
    return c
end

n_sides (generic function with 1 method)

In [14]:
M

140×140 Matrix{Int64}:
  1   1   1   1   1   1   1   1   1   1  …  596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  596  596  633
  1   1   1   1   1   1   1   1   1   1     596  596  596  596  602  602  602
  1   1   1   1   1   1   1   1   1   1  …  596  596  602  602  602  602  602
  1   1   1   1   1   1   2   1   1   1     596  602  602  602  602  602  602
  1   2   1   1   1   1   2   2   1   1     602  602  602  602  602  602  602
  2   2   2   2   2   2   2   1   1   1     602  602  602  602  602  602  602
  2   2   2   2   2   2   2   2   2   2     602  602  602  602  602  602  602
  ⋮                   ⋮                  ⋱              ⋮                 
 20  20  20  21  21  19  21  21  21  21     610  610  610  610  610  610  610
 20  20  20  21  21  21  21  21  21  21     

In [15]:
n_sides(1)

dCartesianIndex(8, 1)
dCartesianIndex(7, 2)
dCartesianIndex(8, 3)
dCartesianIndex(6, 7)
dCartesianIndex(7, 8)
dCartesianIndex(9, 8)
dCartesianIndex(11, 11)
dCartesianIndex(5, 12)
dCartesianIndex(13, 12)
dCartesianIndex(3, 13)
dCartesianIndex(2, 15)
dCartesianIndex(9, 15)


34

In [16]:
price2(v) = n_sides(v) * count(==(v), M)

price2 (generic function with 1 method)

In [17]:
sum(price2.(1:maximum(M)))

dCartesianIndex(8, 1)
dCartesianIndex(7, 2)
dCartesianIndex(8, 3)
dCartesianIndex(6, 7)
dCartesianIndex(7, 8)
dCartesianIndex(9, 8)
dCartesianIndex(11, 11)
dCartesianIndex(5, 12)
dCartesianIndex(13, 12)
dCartesianIndex(3, 13)
dCartesianIndex(2, 15)
dCartesianIndex(9, 15)
dCartesianIndex(16, 1)
dCartesianIndex(10, 2)
dCartesianIndex(15, 2)
dCartesianIndex(16, 5)
dCartesianIndex(17, 6)
dCartesianIndex(16, 7)
dCartesianIndex(8, 8)
dCartesianIndex(13, 11)
dCartesianIndex(12, 12)
dCartesianIndex(28, 1)
dCartesianIndex(26, 2)
dCartesianIndex(25, 3)
dCartesianIndex(26, 4)
dCartesianIndex(29, 6)
dCartesianIndex(30, 7)
dCartesianIndex(18, 8)
dCartesianIndex(29, 8)
dCartesianIndex(17, 9)
dCartesianIndex(30, 9)
dCartesianIndex(24, 10)
dCartesianIndex(29, 11)
dCartesianIndex(24, 12)
dCartesianIndex(27, 12)
dCartesianIndex(33, 1)
dCartesianIndex(32, 4)
dCartesianIndex(36, 5)
dCartesianIndex(27, 6)
dCartesianIndex(33, 7)
dCartesianIndex(40, 1)
dCartesianIndex(41, 3)
dCartesianIndex(40, 4)
dCartesian

821372