In [40]:
I = only.(mapreduce(permutedims, vcat, split.(readlines(open("input")), "")))

141×141 Matrix{Char}:
 '#'  '#'  '#'  '#'  '#'  '#'  '#'  '#'  …  '#'  '#'  '#'  '#'  '#'  '#'  '#'
 '#'  '.'  '.'  '.'  '.'  '.'  '#'  '.'     '#'  '.'  '.'  '.'  '.'  'E'  '#'
 '#'  '.'  '#'  '.'  '#'  '.'  '#'  '.'     '#'  '.'  '#'  '#'  '#'  '.'  '#'
 '#'  '.'  '#'  '.'  '#'  '.'  '.'  '.'     '#'  '.'  '.'  '.'  '#'  '.'  '#'
 '#'  '.'  '#'  '#'  '#'  '.'  '#'  '#'     '#'  '#'  '#'  '.'  '#'  '.'  '#'
 '#'  '.'  '.'  '.'  '#'  '.'  '#'  '.'  …  '.'  '.'  '#'  '.'  '#'  '.'  '#'
 '#'  '.'  '#'  '.'  '#'  '.'  '#'  '.'     '#'  '.'  '#'  '#'  '#'  '.'  '#'
 '#'  '.'  '#'  '.'  '#'  '.'  '.'  '.'     '#'  '.'  '.'  '.'  '.'  '.'  '#'
 '#'  '.'  '#'  '.'  '#'  '.'  '#'  '#'     '#'  '#'  '#'  '#'  '#'  '.'  '#'
 '#'  '.'  '#'  '.'  '#'  '.'  '.'  '.'     '#'  '.'  '.'  '.'  '#'  '.'  '#'
 ⋮                        ⋮              ⋱       ⋮                        ⋮
 '#'  '#'  '#'  '.'  '#'  '#'  '#'  '.'     '#'  '#'  '#'  '#'  '#'  '#'  '#'
 '#'  '.'  '.'  '.'  '#'  '.'  '.'  '.'     

In [41]:
start_node = findfirst(==('S'), I)
end_node = findfirst(==('E'), I)
I[start_node] = '.'
I[end_node] = '.'

'.': ASCII/Unicode U+002E (category Po: Punctuation, other)

In [42]:
unvisited_p::Vector{CartesianIndex} = findall(==('.'), I);

In [43]:
up, right, down, left = CartesianIndex(-1, 0), CartesianIndex(0,1), CartesianIndex(1,0), CartesianIndex(0,-1);

In [44]:
unvisited = [(p,d) for d in [up, right, down, left] for p in unvisited_p]

40468-element Vector{Tuple{CartesianIndex{2}, CartesianIndex{2}}}:
 (CartesianIndex(2, 2), CartesianIndex(-1, 0))
 (CartesianIndex(3, 2), CartesianIndex(-1, 0))
 (CartesianIndex(4, 2), CartesianIndex(-1, 0))
 (CartesianIndex(5, 2), CartesianIndex(-1, 0))
 (CartesianIndex(6, 2), CartesianIndex(-1, 0))
 (CartesianIndex(7, 2), CartesianIndex(-1, 0))
 (CartesianIndex(8, 2), CartesianIndex(-1, 0))
 (CartesianIndex(9, 2), CartesianIndex(-1, 0))
 (CartesianIndex(10, 2), CartesianIndex(-1, 0))
 (CartesianIndex(11, 2), CartesianIndex(-1, 0))
 ⋮
 (CartesianIndex(131, 140), CartesianIndex(0, -1))
 (CartesianIndex(132, 140), CartesianIndex(0, -1))
 (CartesianIndex(134, 140), CartesianIndex(0, -1))
 (CartesianIndex(135, 140), CartesianIndex(0, -1))
 (CartesianIndex(136, 140), CartesianIndex(0, -1))
 (CartesianIndex(137, 140), CartesianIndex(0, -1))
 (CartesianIndex(138, 140), CartesianIndex(0, -1))
 (CartesianIndex(139, 140), CartesianIndex(0, -1))
 (CartesianIndex(140, 140), CartesianIndex(0, -1))

In [45]:
values = Dict(i=>Inf for i in unvisited)
values[(start_node,right)] = 0;

In [46]:
c_rotate = Dict(left=>down, down=>right, right=>up, up=>left)
cc_rotate = Dict(right=>down, down=>left, left=>up, up=>right);

In [47]:
while !isempty(unvisited)
    min_i = argmin([values[i] for i in unvisited])
    curr = unvisited[min_i]
    curr == end_node && break
    curr_val = values[curr]
    
    fwd = curr[1]+curr[2]
    if !(I[fwd] == '#' || !((fwd,curr[2]) in unvisited)) 
        if (values[curr] + 1) < values[(fwd,curr[2])] 
            values[(fwd,curr[2])] = values[curr] + 1
        end
    end
    
    if (values[curr] + 1000) < values[(curr[1], c_rotate[curr[2]])]
        values[(curr[1], c_rotate[curr[2]])] = values[curr] + 1000
    end
    if (values[curr] + 1000) < values[(curr[1], cc_rotate[curr[2]])]
        values[(curr[1], cc_rotate[curr[2]])] = values[curr] + 1000
    end
    
    deleteat!(unvisited, findfirst(==(curr), unvisited));
end

In [51]:
M = zeros(size(I))
for i in 1:size(I,1), j in 1:size(I,2)
    if I[i,j] == '#'
        M[i,j] = -1
    else
        M[i,j] = minimum(values[(CartesianIndex(i,j),d)] for d in [up, left, down, right])
    end
end

In [52]:
M

141×141 Matrix{Float64}:
 -1.0     -1.0     -1.0     -1.0     -1.0  …     -1.0     -1.0     -1.0  -1.0
 -1.0  44246.0  44245.0  44244.0  44243.0     90462.0  90461.0  89460.0  -1.0
 -1.0  45245.0     -1.0  45245.0     -1.0        -1.0     -1.0  89459.0  -1.0
 -1.0  45244.0     -1.0  45246.0     -1.0     92468.0     -1.0  89458.0  -1.0
 -1.0  45243.0     -1.0     -1.0     -1.0     93469.0     -1.0  89457.0  -1.0
 -1.0  45242.0  46241.0  45240.0     -1.0  …  93470.0     -1.0  89456.0  -1.0
 -1.0  45241.0     -1.0  45239.0     -1.0        -1.0     -1.0  89455.0  -1.0
 -1.0  45240.0     -1.0  45238.0     -1.0     88452.0  88453.0  88454.0  -1.0
 -1.0  45239.0     -1.0  45237.0     -1.0        -1.0     -1.0  89455.0  -1.0
 -1.0  45238.0     -1.0  45236.0     -1.0     91462.0     -1.0  89456.0  -1.0
  ⋮                                        ⋱                              ⋮
 -1.0     -1.0     -1.0   3009.0     -1.0        -1.0     -1.0     -1.0  -1.0
 -1.0   1006.0   2007.0   2008.0     -1.0